gap             = 15
border          = 3
border_focus    = 77ccff
border_normal   = 224466
terminal        = alacritty

bind = mod+d            = rofi -show drun -theme-str 'window { transparency: "real"; background-color: #00000055; border: 2px; border-color: #77ccff; border-radius: 12px; }'
bind = mod+b            = firefox
bind = mod+shift+Return = alacritty
bind = mod+ctrl+l       = slock
