gap            = 8
border         = 2
border_focus   = 5588ff
border_normal  = 333333
terminal       = st

# bind = mod+b            = firefox
# bind = mod+shift+Return = alacritty
# bind = mod+ctrl+l       = slock
